name: Auto create PR for add-indexing-summary

on:
  push:
    branches: [ add-indexing-summary ]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR if not exists
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = 'add-indexing-summary';
            const base = 'main';
            const title = 'Add indexing summary';
            const body = 'This PR adds INDEXING_SUMMARY.txt documenting the indexing process and outcomes.';
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, head: `${owner}:${head}`, state: 'open'
            });
            if (prs.length > 0) {
              core.info(`PR already exists: #${prs[0].number}`);
              return;
            }
            const { data: pr } = await github.rest.pulls.create({
              owner, repo, head, base, title, body
            });
            core.info(`Created PR #${pr.number}`);
